### ISSUE TITLE
BUG - Editor mode is not working

### ISSUE THREAD

**Issue by ofreshy** [zalando/zally#993] opened 2019-05-28 15:43 UTC
Trying to paste code into this link is not working for me / team members
https://zally.zalando.net/editor

**Comment by zeitlinger** [comment] 2019-05-29 08:05
Duplicate of #985. (Is not rolled out yet)

**Closed by zeitlinger** 2019-05-29 08:06 UTC

**Comment by zeitlinger** [comment] 2019-05-29 08:43
now it's deployed
