### ISSUE TITLE
YAML spec returns "must use YAML format" violation

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/zally#786] opened 2018-08-10 09:36 UTC
# Reproduce

Go to [Zally](https://zally.zalando.net/) (sadly only internal)

Enter this in the editor.
```yaml
swagger: 2.0
```

Click _Validate_

Result contains this:

> MUST – Provide API Specification using OpenAPI
> must use YAML format
> 
> Rule: https://zalando.github.io/restful-api-guidelines/#101
> 
> Location: paths

# Things that are wrong

- Location should be `/`, not `/paths`
- The message is not true. The specification **IS** in `YAML`.

# Observation

The condition for this is quite clear (in `class UseOpenApiRule`):

```kotlin
    @Check(severity = Severity.MUST)
    fun checkIfTheFormatIsYAML(context: Context): Violation? {
        // at this point the api specification has been already parsed successfully
        // -> the source is either a valid YAML or JSON format
        // -> JSON must start with '{' and end with '}'
        val cleanedUpSource = context.source.trim()
        return if (cleanedUpSource.startsWith("{") && cleanedUpSource.endsWith("}")) {
            context.violation("must use YAML format")
        } else {
            null
        }
    }
```

We need to investigate why is this somehow true when using a YAML source.

**Comment by roxspring** [comment] 2018-08-20 20:05
Not sure if this is relevant but I don't think `swagger: 2.0` is _strictly_ valid. `2.0` will be identified as a `number` but the spec requires a `string`, i.e. `swagger: "2.0"`.

**Comment by roxspring** [comment] 2018-09-05 12:52
@ddufourboivin-zalando are you still able to reproduce this? Looks fixed to me.

**Comment by tkrop** [comment] 2018-09-05 13:40
I agree.

**Comment by roxspring** [comment] 2018-09-05 16:31
With unfortunate timing, one of my colleagues has just run into this issue even though I wasn't able to reproduce earlier. 

Turns out that the reproduction is from a CI pipeline still using an older version of the CLI from before https://github.com/zalando/zally/pull/769, and therefore the CLI is effectively taking all YAML input and converting to JSON before submission. Suspect that @ddufourboivin-zalando must have been using a pre https://github.com/zalando/zally/pull/783 UI where it was doing the same?

Versions of the CLI, UI & Server from master as of today all appear to work together without silent YAML to JSON transformation.

**Comment by roxspring** [comment] 2018-09-24 08:39
Is anybody still able to reproduce this with current versions of server / ui / cli combinations?

**Comment by maxim-tschumak** [comment] 2018-09-24 08:42
I cannot reproduce the problem, closing ...

**Closed by maxim-tschumak** 2018-09-24 08:42 UTC
Labels: bug
