### ISSUE TITLE
Does not match openapi3 schema: Format attribute \"uri-reference\" not supported

### ISSUE THREAD

**Issue by harinarayanan123** [zalando/zally#1171] opened 2020-07-17 20:39 UTC
Hi Team,
Getting the below lint error while linting my document. 
Does not match openapi3 schema: Format attribute \"uri-reference\" not supported
Referred the below links but my schema looks updated
Zally bug : https://github.com/zalando/zally/issues/1138
OpenAPI3.0 schema : https://github.com/zalando/zally/blob/master/server/zally-core/src/main/resources/schemas/openapi3-schema.json
Swagger schema : https://github.com/zalando/zally/blob/master/server/zally-core/src/main/resources/schemas/swagger-schema.json

SAMPLE LINES: (it is failing validation at (#/info/contact/url)
```
openapi: 3.0.0
info:
  title: Title
  description: Some description
  contact:
    name: API Name
    url: www.website.com
    email: email@email.com
  license:
    name: Apache 2.0
  version: 1.0.0
  x-audience: company-internal
  x-api-id: 66f08b6f-4bed
servers:
- url: example.com
  description: desc
- url: example.com
  description: desc
- url: example.com
  description: desc
- url: example.com
  description: desc
```

Please assist.

Thanks!

**Comment by tkrop** [comment] 2021-01-13 08:19
Duplicate of https://github.com/zalando/zally/issues/1176. Is solved.

**Closed by tkrop** 2021-01-13 08:19 UTC
Labels: bug
