### ISSUE TITLE
zally servers fails to start 

### ISSUE THREAD

**Issue by prasenjit-chowdhury-simplisafe** [zalando/zally#1461] opened 2023-08-10 04:49 UTC
MacOs - M2 
Node version 18 

 => ERROR [server 3/3] COPY zally-server/build/libs/zally-server.jar /                                                                                                                   0.0s
------
 > [server 3/3] COPY zally-server/build/libs/zally-server.jar /:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 7931e807-41a0-42d5-ad4a-73b14f22e725::sip1l72to1grp0cesn4jar5h7: "/zally-server/build/libs/zally-server.jar": not found

**Comment by Rogatto** [comment] 2023-08-13 18:56
@prasenjit-chowdhury-simplisafe go to server folder, and run:

`./gradlew clean build`

After that, just go back to the folder that you have the build-and-run.sh, and try again to run it.

**Comment by ePaul** [comment] 2024-01-23 14:04
It looks like the README has some gaps.
Possibly we can also do some additions to the build script.

@ktsypkina will have a look at this.

**Comment by ktsypkina** [comment] 2024-02-19 20:23
before copying server jar it runs
RUN ./gradlew
RUN ./gradlew build

wasn't able to reproduce this error

**Comment by ktsypkina** [comment] 2024-02-19 20:26
since no more issues were created with this problem and no followup is here from this issue author, I would consider to close it.

**Comment by ktsypkina** [comment] 2024-02-21 10:34
@prasenjit-chowdhury-simplisafe could you please tell if the issue was resolved after `./gradlew clean build` ? 
If not, could you please provide more details so we can try to reproduce the issue on our side? 
Thanks!

**Comment by ktsypkina** [comment] 2024-02-21 10:35
@Rogatto could you please tell if you were able to reproduce this issue on your machine?

**Comment by ktsypkina** [comment] 2024-02-21 10:39
Our latest change to `docker-compose.yaml` is fixing this issue:
https://github.com/zalando/zally/pull/1453

> If anyone get the error `ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ea1c9a0c-1d43-4ea5-9790-ed1882c85fce::zarskmsx0awdlxwwmljsqcv1u: "/zally-server/build/libs/zally-server.jar": not found` on main branch `docker-compose up`, this PR also fix that issue.

**Closed** 2024-03-05 13:17 UTC
